management:
  endpoints:
    web:
      exposure:
        include: '*'
        base-path: '/'
logging:
  level:
     org.springframework.web: DEBUG
     guru.springframework.controllers: DEBUG
     org.hibernate: DEBUG        
spring:
  datasource:
    url: jdbc:mysql://139.162.62.230:3306/webot?createDatabaseIfNotExist=true
    username: root
    password: agrima_i876##
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create-drop
    show-sql: true
  application:
    name: project-server
  
server:
  port: 8080    
  
eureka:
  client:
     registerWithEureka: true
     fetchRegistry: true
     serviceUrl:
       defaultZone: http://198.58.126.243:8761/eureka/
  instance:
    hostname: 198.58.126.243
       
  
  